/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const IndexLazyImport = createFileRoute("/")();
const authSigninLazyImport = createFileRoute("/(auth)/sign_in")();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
    path: "/",
    getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

const authSigninLazyRoute = authSigninLazyImport
    .update({
        path: "/sign_in",
        getParentRoute: () => rootRoute,
    } as any)
    .lazy(() => import("./routes/(auth)/sign_in.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            preLoaderRoute: typeof IndexLazyImport;
            parentRoute: typeof rootRoute;
        };
        "/(auth)/sign_in": {
            preLoaderRoute: typeof authSigninLazyImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([IndexLazyRoute, authSigninLazyRoute]);

/* prettier-ignore-end */
